apiVersion: v1
kind: Service
metadata:
  name: mymongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mymongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mymongodb
---
