apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongodb-v1
  namespace: {{ .Release.Namespace }}
  labels:
    app: mymongodb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymongodb
      version: v1
  template:
    metadata:
      labels:
        app: mymongodb
        version: v1
    spec:
      containers:
      - name: mymongodb
        image: {{.Values.image.imageRegistry}}/cs-mymongodb:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
