apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: open-api-viewer
spec:
  rules:
  - services: ["open-api.{{NS}}.svc.cluster.local"]
    methods: ["GET"]

---

apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-open-api-viewer
spec:
  subjects:
  - properties:
      request.auth.claims[role]: "user"
  - properties:
      request.auth.claims[role]: "admin"
  roleRef:
    kind: ServiceRole
    name: "open-api-viewer"