fullnameOverride: coolstore
image:
  repository: https://github.com/vietnam-devs/coolstore-microservices
  pullPolicy: IfNotPresent
  imageRegistry: vndg
  dockerTag: latest

nginx:
  enabled: false

backoffice:
  enabled: false

hosts:
  web: coolstore.local
  backoffice: backoffice.coolstore.local
  api: api.coolstore.local
  idp: id.coolstore.local

gateway:
  ip: 127.0.0.1

idpSettings:
  BasePath: /
  ExternalCurrentUri: http://id.coolstore.local/
  SwaggerRedirectUri: http://api.coolstore.local/swagger/oauth2-redirect.html
  SwaggerPostLogoutRedirectUri: http://api.coolstore.local
  SwaggerAllowedCorsOrigin: http://api.coolstore.local
  SpaAllowedCorsOrigin: http://coolstore.local
  BackOfficeAllowedCorsOrigin: http://backoffice.coolstore.local

catalogSettings:
  NodeEnv: "production"
  Host: "0.0.0.0"
  Port: "5002"
  MongoDbHost: mymongodb
  MongoDbPort: 27017
  MongoDbName: catalog

cartSettings:
  Host: "0.0.0.0"
  Port: "5003"
  MySqlDbFQDN: "mysqldb:3306"
  CatalogUri: "catalog:5002"

inventorySettings:
  Host: "0.0.0.0"
  Port: "5004"
  MySqlDbFQDN: "mysqldb:3306"

ratingSettings:
  NodeEnv: "production"
  Host: "0.0.0.0"
  Port: 5007
  MongoDbHost: mymongodb
  MongoDbPort: 27017
  MongoDbName: rating

graphqlSettings:
  HostsBasePath: /gql/
  CorsOrigins: http://backoffice.coolstore.local/,http://api.coolstore.local/
  IdpAuthority: http://id.coolstore.local/
  IdpAudience: api
  CatalogEndPoint: http://api.coolstore.local/catalog/
  CartEndPoint: http://api.coolstore.local/cart/
  InventoryEndPoint: http://api.coolstore.local/inventory/
  RatingEndPoint: http://api.coolstore.local/rating/

spaSettings:
  NodeEnv: development
  WebUri: http://coolstore.local/
  IdpUri: http://id.coolstore.local/
  OpenApiUri: http://coolstore.local/

backofficeSettings:
  GraphQLEndPoint: http://api.coolstore.local/gql
  Authority: http://id.coolstore.local/
  ClientId: backoffice
  RootUrl: http://backoffice.coolstore.local

openAPISettings:
  CatalogEndPoint: catalog:5002
  CartEndPoint: cart:5003
  InventoryEndPoint: inventory:5004
  RatingEndPoint: rating:5007
