apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: {{ .Release.Namespace }}
  labels:
    app: inventory
spec:
  ports:
  - name: grpc
    port: {{ .Values.inventorySettings.Port }}
    targetPort: {{ .Values.inventorySettings.Port }}
    protocol: TCP
  selector:
    app: inventory
---
