apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "coolstore-jwt-authentication"
spec:
  targets:
  - name: open-api  
  origins:
  - jwt:
      issuer: "http://id.coolstore-msbuild.ml"
      jwksUri: "http://id.coolstore-msbuild.ml/.well-known/openid-configuration/jwks"
      trigger_rules:
      - excluded_paths:
        - exact: /catalog/api/products/ping
  principalBinding: USE_ORIGIN